import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <header className='flex flex-row w-full bg-slate-300 h-20 p-3 items-center'>
          <h1>Welcome</h1>
          <nav>
            <ul className='flex flex-row'>
              <li className='ml-5'>
                <Link href='/'>Home</Link>
              </li>
              <li className='ml-5'>
                <Link href='/blog'>Blog</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
